name: Bump CLI project version

on:
  pull_request:
    types: [opened]
    paths:
      - 'version.txt'

jobs:
  bump-version:
    if: contains(github.head_ref, 'release-please--')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - id: retrieve_version
        run: echo "version=$(cat version.txt)" >> "$GITHUB_OUTPUT"
      - run: chmod +x ./scripts/bump-version.sh
      - run: ./bump-version.sh ${{ steps.retrieve_version.outputs.version }}
        working-directory: scripts
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILE_TO_COMMIT: src/CloudflareDnsync.Cli/CloudflareDnsync.Cli.csproj
        run: |
          export MESSAGE="chore: bump cli project version to ${{ steps.retrieve_version.outputs.version }}"
          export SHA=$( git rev-parse ${{ github.head_ref }}:$FILE_TO_COMMIT )
          export CONTENT=$( base64 -i $FILE_TO_COMMIT )
          gh api --method PUT /repos/:owner/:repo/contents/$FILE_TO_COMMIT \
            --field message="$MESSAGE" \
            --field content="$CONTENT" \
            --field encoding="base64" \
            --field branch="${{ github.head_ref }}" \
            --field sha="$SHA"


  