name: Publish

on:
  repository_dispatch:
    types: [publish-nuget]
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"
      - run: dotnet restore
      - run: chmod +x bump-version.sh
        working-directory: scripts
      - run: ./bump-version.sh ${{ github.event.release.tag_name }}
        working-directory: scripts
      - run: dotnet pack -c Release /p:PackageVersion=${{ github.event.release.tag_name }}
        working-directory: src/CloudflareDnsync.Cli
      - run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_PUBLISH_KEY }}
        working-directory: src/CloudflareDnsync.Cli
