name: Add assets to release

on:
  release:
    types: [published]

jobs:
  upload-assets:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
    - run: dotnet restore
    - run: chmod +x ./build-self-contained.sh
      working-directory: scripts
    - run: ./build-self-contained.sh
      working-directory: scripts
    - uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./scripts/dist/cloudflare-dnsync-*
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
    